### ISSUE TITLE
Доделать UserProfile на backend и frontend

### ISSUE THREAD

**Issue by IAmMum-sAsh** [DRV2VNA/Flats.io#35]
Доработать UserProfile в соответствии с #33 .
В частности:
1. Доработать отображение даты регистрации в личном кабинете
 4. Добавить лайки для пользователя
 5. Добавить отзывы для пользователя

**Comment by DRV2VNA** [comment]
Для хранения _комментариев_ пользователя использовать отдельную таблицу в базе данных (описывается entity) `users_reviews`. Использоваться они будут, как отзывы к риельорам( и людям). По типу оценке в кол-ве звезд. 
**Столбцы в таблице**: 
- id : получается наследованием от BaseEntity, номер записи `NOT NULL`
- reviwer_id : идентификатор, кто оценил `NOT NULL`
- assessed_id : идентификатор, кого оценили `NOT NULL`
- rating : оценка по шкале от 1 до 5 целыми! Т.е. кол-во звезд `NOT NULL`
- comment : комментарий для оценки хранится в формате бд text

При POST запросе пользователя на /api/user/review при передаче JSON будет ставиться оценка в базу.

> Также предусмотреть метод возврата средней оценки по пользователю!

**Comment by DRV2VNA** [comment]
Для лайков необходимо создать endpoint 
- [ ] _/api/likes/get_for_order_  
- [ ] _/api/likes/set_like_ (перенеcти существующий)
- [ ] _/api/likes/get_user_liked_order_

Для этого просто создать новый контроллер с общим путем @RequestMapping("/api/likes").
Так же предусмотреть **LikeService** - класс для работы с репозиторием базы данных лайков.

**Comment by DRV2VNA** [comment]
Лайкать можно квартиры, а писать комментарии с оценкой - риелторам (юзерам)
